[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nock_kernel"
version = "1.2.1"
description = "Jupyter kernel for interactive Nock evaluation."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "N. E. Davis", email = "neal@zorp.io"}
]
keywords = ["nock", "urbit", "interpreter", "pinochle", "nockapp", "nockchain"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Interpreters",
]
dependencies = [
    "mmh3",
    "bitstring",
]

[project.urls]
Homepage = "https://github.com/sigilante/pinochle"
Repository = "https://github.com/sigilante/pinochle"
Issues = "https://github.com/sigilante/pinochle/issues"

[tool.setuptools.package-data]
nock_kernel = ["kernelspec/*.json"]